//===============================================================================
// © 2015 eWorkplace Apps.  ALL rights reserved.
// Main Author: Shrey Sharma
// Original DATE: 4/21/2015
//===============================================================================
package com.eworkplaceapps.platform.userpreference;

/**
 * Created by admin on 4/21/2015.
 */
public class IANATimeZone {

    public enum IANATimeZoneEnum {

        AUSTRALIADARWIN(1),

        AUSTRALIASYDNEY(2),

        AUSTRALIAMELBOURNE(3),

        ASIAKABUL(4),

        AMERICAANCHORAGE(5),

        AMERICAJUNEAU(6),

        AMERICANOME(7),

        AMERICASITKA(8),

        AMERICAYAKUTAT(9),

        ASIABAHRAIN(10),

        ASIAKUWAIT(11),

        ASIAQATAR(12),

        ASIARIYADH(13),

        ASIAADEN(14),

        ASIADUBAI(15),

        ASIAMUSCAT(16),

        ETCGMT4(17),

        AMERICABUENOSAIRES(18),

        AMERICAARGENTINALARIOJA(19),

        AMERICAARGENTINARIOGALLEGOS(20),

        AMERICAARGENTINASALTA(21),

        AMERICAARGENTINASANJUAN(22),

        AMERICAARGENTINASAN_LUIS(23),

        AMERICAARGENTINATUCUMAN(24),

        AMERICAARGENTINAUSHUAIA(25),

        AMERICACATAMARCA(26),

        AMERICACORDOBA(27),

        AMERICAJUJUY(28),

        AMERICAMENDOZA(29),

        ATLANTICBERMUDA(30),

        AMERICAHALIFAX(31),

        AMERICAGLACEBAY(32),

        AMERICAGOOSEBAY(33),

        AMERICAMONCTON(34),

        AMERICATHULE(35),

        ASIABAKU(36),

        AMERICASCORESBYSUND(37),

        ATLANTICAZORES(38),

        AMERICABAHIA(39),

        ASIADHAKA(40),

        ASIATHIMPHU(41),

        AMERICAREGINA(42),

        AMERICASWIFTCURRENT(43),

        ATLANTICCAPEVERDE(44),

        ETCGMT1(45),

        ASIAYEREVAN(46),

        AUSTRALIAADELAIDE(47),

        AUSTRALIABROKENHILL(48),

        AMERICAGUATEMALA(49),

        AMERICABELIZE(50),

        AMERICACOSTARICA(51),

        PACIFICGALAPAGOS(52),

        AMERICAGUATEMAL(53),

        AMERICATEGUCIGALPA(54),

        AMERICAMANAGUA(55),

        AMERICAELSALVADOR(56),

        ETCGMTPLUS6(57),

        ANTARCTICAVOSTOK(58),

        INDIANCHAGOS(59),

        ASIABISHKEK(60),

        ASIAALMATY(61),

        ASIAQYZYLORDA(62),

        ETCGMTMINUS6(63),

        AMERICACUIABA(64),

        AMERICACAMPOGRANDE(65),

        EUROPETIRANE(66),

        EUROPEPRAGUE(67),

        EUROPEBUDAPEST(68),

        EUROPEPODGORICA(69),

        EUROPEBELGRADE(70),

        EUROPELJUBLJANA(71),

        EUROPEBRATISLAVA(72),

        EUROPESARAJEVO(73),

        EUROPEZAGREB(74),

        EUROPESKOPJE(75),

        EUROPEWARSAW(76),

        ANTARCTICAMACQUARIE(77),

        PACIFICPONAPE(78),

        PACIFICKOSRAE(79),

        PACIFICNOUMEA(80),

        PACIFICGUADALCANAL(81),

        PACIFICEFATE(82),

        ETCGMT11(83),

        AMERICAWINNIPEG(84),

        AMERICARAINYRIVER(85),

        AMERICARANKININLET(86),

        AMERICARESOLUTE(87),

        AMERICAMATAMOROS(88),

        AMERICACHICAGO(89),

        AMERICAINDIANAKNOX(90),

        AMERICAINDIANATELLCITY(91),

        AMERICAMENOMINEE(92),

        AMERICANORTHDAKOTABEULAH(93),

        AMERICANORTHDAKOTACENTER(94),

        AMERICANORTHDAKOTANEWSALEM(95),

        CST6CDT(96),

        AMERICAMEXICOCITY(97),

        AMERICABAHIABANDERAS(98),

        AMERICACANCUN(99),

        AMERICAMERIDA(100),

        AMERICAMONTERREY(101),

        ASIASHANGHAI(102),

        ASIACHONGQING(103),

        ASIAHARBIN(104),

        ASIAKASHGAR(105),

        ASIAURUMQI(106),

        ASIAHONGKONG(107),

        ASIAMACAU(108),

        ETCGMT12(109),

        ANTARCTICASYOWA(110),

        AFRICADJIBOUTI(111),

        AFRICAASMERA(112),

        AFRICAADDISABABA(113),

        AFRICANAIROBI(114),

        INDIANCOMORO(115),

        INDIANANTANANARIVO(116),

        AFRICAKHARTOUM(117),

        AFRICAMOGADISHU(118),

        AFRICAJUBA(119),

        AFRICADARESSALAAM(120),

        AFRICAKAMPALA(121),

        INDIANMAYOTTE(122),

        ETCGMT3(123),

        AUSTRALIABRISBANE(124),

        AUSTRALIALINDEMAN(125),

        ASIANICOSIA(126),

        AMERICASAOPAULO(127),

        AMERICANASSAU(128),

        AMERICATORONTO(129),

        AMERICAIQALUIT(130),

        AMERICAMONTREAL(131),

        AMERICANIPIGON(132),

        AMERICAPANGNIRTUNG(133),

        AMERICATHUNDERBAY(134),

        AMERICAGRANDTURK(135),

        AMERICANEWYORK(136),

        AMERICADETROIT(137),

        AMERICAINDIANAPETERSBURG(138),

        AMERICAINDIANAVINCENNES(139),

        AMERICAINDIANAWINAMAC(140),

        AMERICAKENTUCKYMONTICELLO(141),

        AMERICALOUISVILLE(142),

        EST5EDT(143),

        AFRICACAIRO(144),

        ASIAGAZA(145),

        ASIAHEBRON(146),

        ASIAYEKATERINBURG(147),

        EUROPEMARIEHAMN(148),

        EUROPESOFIA(149),

        EUROPETALLINN(150),

        EUROPEHELSINKI(151),

        EUROPEVILNIUS(152),

        EUROPERIGA(153),

        EUROPEKIEV(154),

        EUROPESIMFEROPOL(155),

        EUROPEUZHGOROD(156),

        EUROPEZAPOROZHYE(157),

        PACIFICFIJI(158),

        ATLANTICCANARY(159),

        ATLANTICFAEROE(160),

        EUROPELONDON(161),

        EUROPEGUERNSEY(162),

        EUROPEDUBLIN(163),

        EUROPEISLEOFMAN(164),

        EUROPEJERSEY(165),

        EUROPELISBON(166),

        ATLANTICMADEIRA(167),

        EUROPEATHENS(168),

        EUROPECHISINAU(169),

        EUROPEBUCHAREST(170),

        ASIATBILISI(171),

        AMERICAGODTHAB(172),

        AFRICAOUAGADOUGOU(173),

        AFRICAABIDJAN(174),

        AFRICAELAAIUN(175),

        AFRICAACCRA(176),

        AFRICABANJUL(177),

        AFRICACONAKRY(178),

        AFRICABISSAU(179),

        ATLANTICREYKJAVIK(180),

        AFRICAMONROVIA(181),

        AFRICABAMAKO(182),

        AFRICANOUAKCHOTT(183),

        ATLANTICSTHELENA(184),

        AFRICAFREETOWN(185),

        AFRICADAKAR(186),

        AFRICASAOTOME(187),

        AFRICALOME(188),

        PACIFICRAROTONGA(189),

        PACIFICTAHITI(190),

        PACIFICFAKAOFO(191),

        PACIFICJOHNSTON(192),

        PACIFICHONOLULU(193),

        ETCGMT10(194),

        ASIAKOLKATA(195),

        ASIATEHRAN(196),

        ASIAJERUSALEM(197),

        ASIAAMMAN(198),

        EUROPEMINSK(199),

        EUROPEKALININGRAD(200),

        ASIAPYONGYANG(201),

        ASIASEOUL(202),

        ASIAMAGADAN(203),

        ASIAANADYR(204),

        ASIAKAMCHATKA(205),

        INDIANMAURITIUS(206),

        INDIANREUNION(207),

        INDIANMAHE(208),

        ASIABEIRUT(209),

        AMERICAMONTEVIDEO(210),

        AFRICACASABLANCA(211),

        AMERICAEDMONTON(212),

        AMERICACAMBRIDGEBAY(213),

        AMERICAINUVIK(214),

        AMERICAYELLOWKNIFE(215),

        AMERICAOJINAGA(216),

        AMERICADENVER(217),

        AMERICABOISE(218),

        AMERICASHIPROCK(219),

        MST7MDT(220),

        AMERICACHIHUAHUA(221),

        AMERICAMAZATLAN(222),

        INDIANCOCOS(223),

        ASIARANGOON(224),

        ASIANOVOSIBIRSK(225),

        ASIANOVOKUZNETSK(226),

        ASIAOMSK(227),

        AFRICAWINDHOEK(228),

        ASIAKATMANDU(229),

        ANTARCTICASOUTHPOLE(230),

        ANTARCTICAMCMURDO(231),

        PACIFICAUCKLAND(232),

        AMERICASTJOHNS(233),

        ASIAIRKUTSK(234),

        ASIAKRASNOYARSK(235),

        ANTARCTICAPALMER(236),

        AMERICASANTIAGO(237),

        AMERICAVANCOUVER(238),

        AMERICADAWSON(239),

        AMERICAWHITEHORSE(240),

        AMERICATIJUANA(241),

        AMERICALOS_ANGELES(242),

        PST8PDT(243),

        AMERICASANTAISABEL(244),

        ASIAKARACHI(245),

        AMERICAASUNCION(246),

        EUROPEBRUSSELS(247),

        EUROPECOPENHAGEN(248),

        EUROPEMADRID(249),

        AFRICACEUTA(250),

        EUROPEPARIS(251),

        EUROPEMOSCOW(252),

        EUROPESAMARA(253),

        EUROPEVOLGOGRAD(254),

        ANTARCTICAROTHERA(255),

        AMERICAFORTALEZA(256),

        AMERICAARAGUAINA(257),

        AMERICABELEM(258),

        AMERICAMACEIO(259),

        AMERICARECIFE(260),

        AMERICASANTAREM(261),

        AMERICACAYENNE(262),

        AMERICAPARAMARIBO(263),

        ETCGMTPLUS3(264),

        AMERICACORALHARBOUR(265),

        AMERICABOGOTA(266),

        AMERICAGUAYAQUIL(267),

        AMERICAPORTAUPRINCE(268),

        AMERICAJAMAICA(269),

        AMERICACAYMAN(270),

        AMERICAPANAMA(271),

        AMERICALIMA(272),

        ETCGMT5(273),

        AMERICAANTIGUA(274),

        AMERICAANGUILLA(275),

        AMERICAARUBA(276),

        AMERICABARBADOS(277),

        AMERICA7STBARTHELEMY(278),

        AMERICALAPAZ(279),

        AMERICAMANAUS(280),

        AMERICABOAVISTA(281),

        AMERICAEIRUNEPE(282),

        AMERICAPORTOVELHO(283),

        AMERICARIOBRANCO(284),

        AMERICABLANCSABLON(285),

        AMERICACURACAO(286),

        AMERICADOMINICA(287),

        AMERICASANTO_DOMINGO(288),

        AMERICAGRENADA(289),

        AMERICAGUADELOUPE(290),

        AMERICAGUYANA(291),

        AMERICAST_KITTS(292),

        AMERICASTLUCIA(293),

        AMERICAMARIGOT(294),

        AMERICAMARTINIQUE(295),

        AMERICAMONTSERRAT(296),

        AMERICAPUERTORICO(297),

        AMERICAPORTOFSPAIN(298),

        AMERICASTVINCENT(299),

        AMERICATORTOLA(300),

        AMERICASTTHOMAS(301),

        ETCGMTPLUS4(302),

        ANTARCTICADAVIS(303),

        INDIANCHRISTMAS(304),

        ASIAJAKARTA(305),

        ASIAPONTIANAK(306),

        ASIAPHNOMPENH(307),

        ASIAVIENTIANE(308),

        ASIAHOVD(309),

        ASIABANGKOK(310),

        ASIASAIGON(311),

        ETCGMT7(312),

        PACIFICAPIA(313),

        ASIABRUNEI(314),

        ASIAMAKASSAR(315),

        ASIAKUALALUMPUR(316),

        ASIAKUCHING(317),

        ASIAMANILA(318),

        ASIASINGAPORE(319),

        ETCGMT8(320),

        AFRICABUJUMBURA(321),

        AFRICAGABORONE(322),

        AFRICALUBUMBASHI(323),

        AFRICAMASERU(324),

        AFRICATRIPOLI(325),

        AFRICABLANTYRE(326),

        AFRICAMAPUTO(327),

        AFRICAKIGALI(328),

        //("AFRICA/MBABANE""SOUTH AFRICA STANDARD TIME""SZ")]
        AFRICAMBABANE(329),

        //(AFRICA/JOHANNESBURG""SOUTH AFRICA STANDARD TIME""ZA")]
        AFRICAJOHANNESBURG(330),

        //("AFRICA/LUSAKA""SOUTH AFRICA STANDARD TIME""ZM")]
        AFRICALUSAKA(331),

        //("AFRICA/HARARE""SOUTH AFRICA STANDARD TIME""ZW")]
        AFRICAHARARE(332),

        //("ETC/GMT-2""SOUTH AFRICA STANDARD TIME""ZZ")]
        ETCGMT2(333),

        //(" ASIA/COLOMBO""SRI LANKA STANDARD TIME""LK")]
        ASIACOLOMBO(334),

        //(" ASIA/DAMASCUS""SYRIA STANDARD TIME""SY")]
        ASIADAMASCUS(335),

        //(" ASIA/TAIPEI""TAIPEI STANDARD TIME""TW")]
        ASIATAIPEI(336),

        //(" AUSTRALIA/HOBART""TASMANIA STANDARD TIME""AU")]
        AUSTRALIAHOBART(337),

        //(" AUSTRALIA/CURRIE""TASMANIA STANDARD TIME""AU")]
        AUSTRALIACURRIE(338),

        //(" ASIA/TOKYO""TOKYO STANDARD TIME""JP")]
        ASIATOKYO(339),

        //(" ASIA/JAYAPURA""TOKYO STANDARD TIME""ID")]
        ASIAJAYAPURA(340),

        //("PACIFIC/PALAU""TOKYO STANDARD TIME""PW")]
        PACIFICPALAU(341),

        //(" ASIA/DILI""TOKYO STANDARD TIME""TL")]
        ASIADILI(342),

        //("ETC/GMT-9""TOKYO STANDARD TIME""ZZ")]
        ETCGMT9(343),

        //("PACIFIC/ENDERBURY""TONGA STANDARD TIME""KI")]
        PACIFICENDERBURY(344),

        //("PACIFIC/TONGATAPU""TONGA STANDARD TIME""TO")]
        PACIFICTONGATAPU(345),

        //("ETC/GMT-13""TONGA STANDARD TIME""ZZ")]
        ETCGMT13(346),

        //(" EUROPE/ISTANBUL""TURKEY STANDARD TIME""TR")]
        EUROPEISTANBUL(347),

        //(" AMERICA/ INDIANAPOLIS""US EASTERN STANDARD TIME""US")]
        AMERICAINDIANAPOLIS(348),

        //(" AMERICA/ INDIANA/MARENGO""US EASTERN STANDARD TIME""US")]
        AMERICAINDIANAMARENGO(349),

        //(" AMERICA/ INDIANA/VEVAY""US EASTERN STANDARD TIME""US")]
        AMERICAINDIANAVEVAY(350),

        //(" AMERICA/DAWSON_CREEK""US MOUNTAIN STANDARD TIME""CA")]
        AMERICADAWSONCREEK(351),

        //(" AMERICA/HERMOSILLO""US MOUNTAIN STANDARD TIME""MX")]
        AMERICAHERMOSILLO(352),

        //(" AMERICA/PHOENIX""US MOUNTAIN STANDARD TIME""US")]
        AMERICAPHOENIX(353),

        //("ETC/GMT+7""US MOUNTAIN STANDARD TIME""ZZ")]
        ETCGMTPLUS7(354),

        //("ETC/GMT""UTC""GL")]
        ETCGMT(355),

        //(" AMERICA/DANMARKSHAVN""UTC""ZZ")]
        AMERICADANMARKSHAVN(356),

        //("PACIFIC/TARAWA""UTC+12""KI")]
        PACIFICTARAWA(357),

        //("PACIFIC/MAJURO""UTC+12""MH")]
        PACIFICMAJURO(358),

        //("PACIFIC/KWAJALEIN""UTC+12""MH")]
        PACIFICKWAJALEIN(359),


        PACIFICNAURU(360),


        PACIFICFUNAFUTI(361),

        PACIFICWAKE(362),

        PACIFICWALLIS(363),

        ETCGMTMINUS12(364),

        AMERICANORONHA(365),

        ATLANTICSOUTH_GEORGIA(366),

        ETCGMTPLUS2(367),

        PACIFICPAGO_PAGO(368),

        PACIFICNIUE(369),

        PACIFICMIDWAY(370),

        ETCGMTPLUS11(372),

        ASIAULAANBAATAR(373),

        ASIACHOIBALSAN(374),

        AMERICACARACAS(375),

        ASIAVLADIVOSTOK(376),

        ASIASAKHALIN(377),

        AUSTRALIAPERTH(378),

        ANTARCTICAY(379),

        AFRICALUANDA(380),

        AFRICAPORTONOVO(381),

        AFRICAKINSHASA(382),

        AFRICABANGUI(383),

        AFRICABRAZZAVILLE(384),

        AFRICADOUALA(385),

        AFRICAALGIERS(386),

        AFRICALIBREVILLE(387),

        AFRICAMALABO(388),

        AFRICANIAMEY(389),

        AFRICALAGOS(390),

        AFRICANDJAMENA(391),

        AFRICATUNIS(392),

        ETCGMTMINUS1(393),

        EUROPEANDORRA(394),

        EUROPEVIENNA(395),

        EUROPEZURICH(396),

        EUROPEBERLIN(397),

        EUROPEGIBRALTAR(398),

        EUROPEROME(399),

        EUROPEVADUZ(400),

        EUROPELUXEMBOURG(401),

        EUROPEMONACO(402),

        EUROPEMALTA(403),

        EUROPEAMSTERDAM(404),

        EUROPEOSLO(405),

        EUROPESTOCKHOLM(406),

        ARCTICLONGYEARBYEN(407),

        EUROPESANMARINO(408),

        EUROPEVATICAN(409),

        ANTARCTICAMAWSON(410),

        ASIAORAL(411),

        ASIAAQTAU(412),

        ASIAAQTOBE(413),

        INDIANMALDIVES(414),

        INDIANKERGUELEN(415),

        ASIADUSHANBE(416),

        ASIAASHGABAT(417),

        ASIATASHKENT(418),

        ASIASAMARKAND(419),

        ETCGMTMINUS5(420),

        ANTARCTICADUMONTDURVILLE(421),

        PACIFICTRUK(422),

        PACIFICGUAM(423),

        PACIFICSAIPAN(424),

        PACIFICPORTMORESBY(425),

        ETCGMTMINUS10(426),

        ASIAYAKUTSK(427),

        ASIACALCUTTA(428),

        AMERICAARGENTINABUENOSAIRES(429),

        AMERICAARGENTINACATAMARCA(430),

        AMERICAATIKOKAN(431),

        AMERICAARGENTINACORDOBA(432),

        AMERICAARGENTINAJUJUY(433),

        ASIAKATHMANDU(434),

        AMERICA_ADAK(435),

        PACIFIC_GAMBIER(436),

        PACIFIC_PIT_CAIRN(437),

        ETC_UTC(438),

        PACIFIC_KIRITI_MATI(439),

        PACIFIC_CHAT_HAM(440),

        PACIFIC_NOR_FOLK(441),

        GMT(442),

        AUSTRALIA_LORD_HOWE(443),

        US_EASTERN(444),

        US_MOUNTAIN(445),

        US_CENTRAL(446),

        US_PACIFIC(447),

        AUSTRALIA_CANBERRA(448),

        AMERICA_VIRGIN(449),

        AMERICA_METLAKATLA(500),

        AMERICA_CRESTON(501),

        AMERICA_CHIHUAHUA(502),

        AMERICA_HAVANA(503),

        AMERICA_ARGENTINA_MENDOZA(504);

        private int id;

        IANATimeZoneEnum(int id) {
            this.id = id;
        }

        public int getId() {
            return id;
        }
    }
}
